version: '3.8'
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    # volumes:
    #   - ./local_pgdata:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - 8080:80
  #   env_file:
  #     - pgadmin.env
    # volumes:
    #   - ./pgadmin-data:/var/lib/pgadmin
  redis:
    image: redis
    container_name: local_redis
    restart: always
    ports:
      - 6379:6379
    # volumes:
    #   - ./local_redisdata:/data
